name: hero
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2

  flutter_riverpod: ^2.0.0-dev.9
  json_serializable: ^6.3.2

  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/window_size

  flutter_form_builder: ^7.2.0
  form_builder_image_picker: ^3.1.0
  form_builder_validators: ^8.1.1
  form_builder_extra_fields: ^8.3.0

  rounded_loading_button: ^2.1.0

  modal_bottom_sheet: ^2.1.0

  dotted_border: ^2.0.0+2

  flutter_secure_storage: ^5.0.2
  flutter_auth:
    path: ../../../gitlab/flutter_auth
    # git:
    #   url: https://curth.dev/opensource/flutter_auth

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.1

flutter:
  uses-material-design: true
  generate: true
