name: hero
description: A new Flutter project.
publish_to: "none"

version: 0.0.7+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2

  http: ^0.13.5
  intl: ^0.17.0
  go_router: ^5.1.1
  flutter_riverpod: ^2.1.0
  freezed_annotation: ^2.1.0
  json_annotation: ^4.7.0
  uuid: ^3.0.6
  flutter_flavor: ^3.1.1
  collection:

  shared_preferences: ^2.0.15
  flutter_secure_storage: ^5.0.2
  flutter_gravatar: ^2.0.2

  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/window_size

  flutter_form_builder: ^7.2.0
  form_builder_image_picker: ^3.1.0
  form_builder_validators: ^8.1.1
  form_builder_extra_fields: ^8.3.0
  desktop_drop: ^0.3.3
  mime: ^1.0.2
  flutter_iconpicker: ^3.2.2
  flutter_touch_spin: ^2.0.0
  file_picker:

  rounded_loading_button: ^2.1.0
  modal_bottom_sheet: ^2.1.2
  dotted_border: ^2.0.0+2
  salomon_bottom_bar: ^3.3.1
  custom_pop_up_menu: ^1.2.4
  font_awesome_flutter: ^10.2.1
  url_launcher: ^6.1.6
  flutter_speed_dial: ^6.2.0
  flutter_layout_grid: ^2.0.1
  just_the_tooltip:

  flutter_auth:
    git:
      url: https://curth.dev/opensource/flutter_auth

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.1
  freezed: ^2.1.1
  json_serializable: ^6.4.0
  msix: ^3.7.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/app_icon/icon.png

msix_config:
  display_name: Hero App
  publisher:
  publisher_display_name: Jonas Curth
  identity_name: 
  logo_path: assets/app_icon/play_store_512.png
  capabilities: internetClient
  languages: de-de
  store: true
  app_installer:  
    hours_between_update_checks: 0
    automatic_background_task: true
    update_blocks_activation: true
    show_prompt: true
    force_update_from_any_version: false