name: hero
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  json_serializable: ^6.3.2

  flutter_form_builder: ^7.2.0
  form_builder_image_picker: ^3.1.0
  form_builder_validators: ^8.1.1
  form_builder_extra_fields: ^8.3.0

  rounded_loading_button: ^2.1.0

  modal_bottom_sheet: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.1

flutter:
  uses-material-design: true
  generate: true
