name: hero
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2

  http: ^0.13.5
  go_router: ^5.0.5
  flutter_riverpod: ^2.0.0-dev.9
  freezed_annotation: ^2.1.0
  json_annotation: ^4.7.0

  flutter_secure_storage: ^5.0.2
  flutter_gravatar: ^2.0.2

  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/window_size

  flutter_form_builder: ^7.2.0
  form_builder_image_picker: ^3.1.0
  form_builder_validators: ^8.1.1
  form_builder_extra_fields: ^8.3.0

  rounded_loading_button: ^2.1.0
  modal_bottom_sheet: ^2.1.2
  dotted_border: ^2.0.0+2
  flutter_slidable: ^2.0.0
  salomon_bottom_bar: ^3.3.1
  custom_pop_up_menu: ^1.2.4
  font_awesome_flutter: ^10.2.1

  flutter_auth:
    git:
      url: https://curth.dev/opensource/flutter_auth

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.1
  freezed: ^2.1.1
  json_serializable: ^6.4.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icon.png
